<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>DEBUG;TRACE;LOG_INFO</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DefineConstants>TRACE;LOG_INFO</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Lib'">
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <Target Name="BuildBoth" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <MSBuild Projects="$(MSBuildProjectFile)"
             Targets="Build"
             Properties="Configuration=Lib" />
  </Target>
</Project>
